apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: recsys
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "recsys_db"
  LOG_LEVEL: "INFO"
  FEATURE_STORE_PATH: "/data/feature_store"
