apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: recsys
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: kafka:latest
          ports:
            - containerPort: 9092
