apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: recsys
spec:
  type: ClusterIP
  selector:
    app: recommendation-service
  ports:
    - port: 8003
      targetPort: 8003
